/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-06 13:12:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.trail;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import trail.model.vo.Trail;
import java.util.ArrayList;
import tag.model.vo.Tag;
import member.model.vo.Member;
import java.util.ArrayList;
import trail.model.vo.Trail;
import follow.model.vo.Follow;
import javax.servlet.http.HttpSession;

public final class search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/trail/../common/footer.jsp", Long.valueOf(1693144244000L));
    _jspx_dependants.put("/views/trail/../common/navbar.jsp", Long.valueOf(1694005937110L));
    _jspx_dependants.put("/views/trail/../common/head.jsp", Long.valueOf(1693643825518L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.servlet.http.HttpSession");
    _jspx_imports_classes.add("follow.model.vo.Follow");
    _jspx_imports_classes.add("tag.model.vo.Tag");
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("trail.model.vo.Trail");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"/fm/views/common/error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\" data-bs-theme=\"auto\">\n");
      out.write("<head>\n");
      out.write("	<link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"/fm/apple-touch-icon.png\">\n");
      out.write("<link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"/fm/favicon-32x32.png\">\n");
      out.write("<link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"/fm/favicon-16x16.png\">\n");
      out.write("<link rel=\"manifest\" href=\"/fm/site.webmanifest\">\n");
      out.write("\n");
      out.write("		<meta charset=\"utf-8\">\n");
      out.write("		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("		<meta name=\"description\" content=\"\">\n");
      out.write("		<title>FollowMe! Trail Sharing SNS</title>\n");
      out.write("	\n");
      out.write("<!-- 		<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/@docsearch/css@3\"> -->\n");
      out.write("\n");
      out.write("<!-- 부트스트랩, 부트스트랩 아이콘 css, js,  jquery 로드 -->	\n");
      out.write("	<link href=\"/fm/resources/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css\">\n");
      out.write("\n");
      out.write("	<script src=\"/fm/resources/js/jquery-3.7.0.min.js\"></script>\n");
      out.write("	<script src=\"/fm/resources/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- 수제 css , js 로드 -->\n");
      out.write("	<link href=\"/fm/resources/css/fm.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("	<script src=\"/fm/resources/js/fm.js\"></script>\n");
      out.write("	\n");
      out.write('\n');

ArrayList<Trail> list = (ArrayList<Trail>) request.getAttribute("list");
ArrayList<String> searchHistory = (ArrayList<String>) session.getAttribute("searchHistory");

      out.write("\n");
      out.write("<!-- 상단 고정 내비게이션 바 -->\n");
      out.write("\r\n");
      out.write("\r\n");

	Member loginMember = (Member)session.getAttribute("loginMember");


      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("        var navLinks = document.querySelectorAll(\".nav-li a\");\r\n");
      out.write("\r\n");
      out.write("        for (var i = 0; i < navLinks.length; i++) {\r\n");
      out.write("            navLinks[i].addEventListener(\"mouseover\", function (event) {\r\n");
      out.write("                this.classList.add(\"highlighted\");\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            navLinks[i].addEventListener(\"mouseout\", function (event) {\r\n");
      out.write("                this.classList.remove(\"highlighted\");\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"top-bar\"></div>\r\n");
      out.write("<div class=\"head-div2\">\r\n");
      out.write("	<div class=\"nav-div2 container\">\r\n");
      out.write("		<ul class=\"nav-ul2\">\r\n");
      out.write("			<li class=\"nav-li2\"><a href=\"/fm/tlist\">HOME</a></li>\r\n");
      out.write("			<li class=\"nav-li2\"><a href=\"/fm/views/trail/create.jsp\">TRAIL</a></li>\r\n");
      out.write("			<li class=\"nav-li2\"><a href=\"/fm/msgcol\">MESSAGE</a></li>\r\n");
      out.write("			<li class=\"nav-li2\"><a href=\"/fm/flist?mid=");
      out.print( loginMember.getmId() );
      out.write("\">FOLLOW</a></li>\r\n");
      out.write("			<li class=\"nav-li2\" id=\"myProfile\"><a href=\"/fm/myinfo\">MYPROFILE</a></li>\r\n");
      out.write("			<li class=\"nav-li2\"><a href=\"/fm/nlist\">NOTICE</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"nav-search2\">\r\n");
      out.write("	<img class=\"search-icon2\" src=\"/fm/resources/img/search.jpeg\" onclick=\"search();\">\r\n");
      out.write("	<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"25\" height=\"25\" fill=\"currentColor\" class=\"bi bi-box-arrow-right\" viewBox=\"0 0 16 16\" onclick=\"logout();\" style=\"cursor: pointer;\">\r\n");
      out.write("	    <path fill-rule=\"evenodd\" d=\"M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z\"/>\r\n");
      out.write("	    <path fill-rule=\"evenodd\" d=\"M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z\"/>\r\n");
      out.write("	</svg>\r\n");
      out.write("	</svg>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"main-logo-img2\">\r\n");
      out.write("		<a href=\"/fm/pheonix.jsp\"><img class=\"logo-img2\" src=\"/fm/resources/img/Followmelogo.png\"></a>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function logout(){\r\n");
      out.write("	location.href=\"/fm/logout\"\r\n");
      out.write("}\r\n");
      out.write("function search(){\r\n");
      out.write("	location.href=\"/fm/views/trail/search.jsp\"\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(".followee {\n");
      out.write("	position: fixed;\n");
      out.write("	margin-top: 20px; /* 위쪽 여백 설정 */\n");
      out.write("	top: 400px; /* 원하는 상단 간격 설정 */\n");
      out.write("	right: 0px;\n");
      out.write("	padding: 50px; /* 내부 여백 설정 */\n");
      out.write("	max-width: 400px; /* 최대 너비 설정 */\n");
      out.write("	box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.1); /* 그림자 효과 추가 */\n");
      out.write("}\n");
      out.write("\n");
      out.write("#selectFolloweeRank {\n");
      out.write("	width: 100%; /* 테이블 너비 100%로 설정 */\n");
      out.write("	border-collapse: collapse; /* 테이블 셀 간 경계 없앰 */\n");
      out.write("}\n");
      out.write("\n");
      out.write("#selectFolloweeRank th, #selectFolloweeRank td {\n");
      out.write("	border: 1px solid #ccc; /* 셀 테두리 설정 */\n");
      out.write("	padding: 8px; /* 셀 내부 여백 설정 */\n");
      out.write("	text-align: center; /* 셀 가운데 정렬 */\n");
      out.write("}\n");
      out.write("\n");
      out.write("#selectFolloweeRank th {\n");
      out.write("	background-color: #f2f2f2; /* 헤더 배경색 설정 */\n");
      out.write("}\n");
      out.write("\n");
      out.write(".weeklytag {\n");
      out.write("	position: fixed;\n");
      out.write("	top: 100px; /* 원하는 상단 간격 설정 */\n");
      out.write("	right: 0;\n");
      out.write("	float: right; /* 오른쪽 정렬 */\n");
      out.write("	margin-right: 20px; /* 오른쪽 여백 설정 */\n");
      out.write("	background-color: white;\n");
      out.write("	/* 다른 요소 위에 보이도록 설정 */\n");
      out.write("}\n");
      out.write("\n");
      out.write(".card-container {\n");
      out.write("	overflow: hidden; /* 자식 요소가 넘치는 경우를 방지합니다. */\n");
      out.write("}\n");
      out.write("\n");
      out.write(".card {\n");
      out.write("	width: 300px;\n");
      out.write("	margin-right: 10px;\n");
      out.write("	float: left; /* 카드를 가로로 나열합니다. */\n");
      out.write("	margin-bottom: 10px; /* 필요에 따라 아래 여백을 조절합니다. */\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<script type=\"text/javascript\"\n");
      out.write("		src=\"/fm/resources/js/jquery-3.7.0.min.js\"></script>\n");
      out.write("	<div class=\"container\">\n");
      out.write("		<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("\n");
      out.write("			$(function() {\n");
      out.write("\n");
      out.write("				\n");
      out.write("\n");
      out.write("				$.ajax({\n");
      out.write("							url : \"/fm/weeklymax\",\n");
      out.write("							type : \"get\",\n");
      out.write("							dataType : \"json\",\n");
      out.write("							success : function(data) {\n");
      out.write("								console.log(\"주간 조회순 게시글 : \" + data);\n");
      out.write("\n");
      out.write("								var str = JSON.stringify(data);\n");
      out.write("								var json = JSON.parse(str);\n");
      out.write("\n");
      out.write("								values = \"<input type='submit' value='더 많은 결과 보기'><br><br>\";\n");
      out.write("								for ( var i in json.nlist) {\n");
      out.write("									values += \"<div class='card'>\"\n");
      out.write("											+ \"<img class='card-img-top' src='https://dummyimage.com/450x300/dee2e6/6c757d.jpg' alt='...' />\"\n");
      out.write("											+ \"<div class='card-body'>\"\n");
      out.write("											+ \"<h5 class='card-title'> \"\n");
      out.write("											+ json.nlist[i].nickName\n");
      out.write("											+ \"님</h5>\"\n");
      out.write("											+ \"<p class='card-text'> 작성 날짜: \"\n");
      out.write("											+ json.nlist[i].trailDate\n");
      out.write("											+ \"<br> JSON: \"\n");
      out.write("											+ json.nlist[i].trailJson\n");
      out.write("											+ \"<br> 조회수:\"\n");
      out.write("											+ json.nlist[i].trailCount\n");
      out.write("											+ \" <br> </p>\"\n");
      out.write("											+\n");
      out.write("\n");
      out.write("											\"<a href='/fm/tdetail?trailId=\"\n");
      out.write("											+ json.nlist[i].trailId\n");
      out.write("											+ \"' class='btn btn-primary'>상세보기</a>\"\n");
      out.write("											+ \"</div>\" + \"</div>\";\n");
      out.write("\n");
      out.write("								}\n");
      out.write("								$('#selectWeeklycount')\n");
      out.write("										.html(\n");
      out.write("												$('#selectWeeklycount').html()\n");
      out.write("														+ values);\n");
      out.write("							},\n");
      out.write("\n");
      out.write("							error : function(xhr, status, error) {\n");
      out.write("								console.error(\"주간 조회순 게시물 가져오기 에러 : \", error);\n");
      out.write("							}\n");
      out.write("\n");
      out.write("						});//ajax\n");
      out.write("\n");
      out.write("				$\n");
      out.write("						.ajax({\n");
      out.write("							url : \"/fm/weeklygood\",\n");
      out.write("							type : \"get\",\n");
      out.write("							dataType : \"json\",\n");
      out.write("							success : function(data) {\n");
      out.write("								console.log(\"주간 좋아요 게시글 : \" + data);\n");
      out.write("\n");
      out.write("								var str = JSON.stringify(data);\n");
      out.write("								var json = JSON.parse(str);\n");
      out.write("\n");
      out.write("								values = \"<input type='submit' value='더 많은 결과 보기'><br><br>\";\n");
      out.write("								for ( var i in json.glist) {\n");
      out.write("									values += \"<div class='card'>\"\n");
      out.write("											+ \"<img class='card-img-top' src='https://dummyimage.com/450x300/dee2e6/6c757d.jpg' alt='...' />\"\n");
      out.write("											+ \"<div class='card-body'>\"\n");
      out.write("											+ \"<h5 class='card-title'>\"\n");
      out.write("											+ json.glist[i].nickName\n");
      out.write("											+ \"님</h5>\"\n");
      out.write("											+ \"<p class='card-text'> 작성 날짜: \"\n");
      out.write("											+ json.glist[i].trailDate\n");
      out.write("											+ \"<br> JSON\"\n");
      out.write("											+ json.glist[i].trailJson\n");
      out.write("											+ \"<br> 좋아요 : \"\n");
      out.write("											+ json.glist[i].trailGood\n");
      out.write("											+ \" <br> </p>\"\n");
      out.write("											+\n");
      out.write("\n");
      out.write("											\"<a href='/fm/tdetail?trailId=\"\n");
      out.write("											+ json.glist[i].trailId\n");
      out.write("											+ \"' class='btn btn-primary'>상세보기</a>\"\n");
      out.write("											+ \"</div>\" + \"</div>\";\n");
      out.write("								}\n");
      out.write("								$('#selectWeeklygood').html(\n");
      out.write("										$('#selectWeeklygood').html() + values);\n");
      out.write("							},\n");
      out.write("\n");
      out.write("							error : function(xhr, status, error) {\n");
      out.write("								console.error(\"주간 좋아요 게시물 가져오기 에러 : \", error);\n");
      out.write("							}\n");
      out.write("\n");
      out.write("						});//ajax\n");
      out.write("\n");
      out.write("				$.ajax({\n");
      out.write("					url : \"/fm/weeklyonetag\",\n");
      out.write("					type : \"get\",\n");
      out.write("					dataType : \"json\",\n");
      out.write("					success : function(data) {\n");
      out.write("						console.log(\"태그 1위 가져오기 : \" + data);\n");
      out.write("\n");
      out.write("						var str = JSON.stringify(data);\n");
      out.write("						var json = JSON.parse(str);\n");
      out.write("\n");
      out.write("						values = \"\";\n");
      out.write("						// 첫 번째 요소만 가져오기\n");
      out.write("						var firstTag = json.olist[0];\n");
      out.write("\n");
      out.write("						// 첫 번째 요소의 \"tag\" 값을 사용하여 HTML 생성\n");
      out.write("						values += \"<h3> 태그 : #\" + firstTag.tag + \"</h3>\";\n");
      out.write("						$('#onetag').html($('#onetag').html() + values);\n");
      out.write("					},\n");
      out.write("					error : function(xhr, status, error) {\n");
      out.write("						console.error(\"인기 태그 한개 가져오기 에러 : \", error);\n");
      out.write("					}\n");
      out.write("\n");
      out.write("				});//ajax\n");
      out.write("\n");
      out.write("				$\n");
      out.write("						.ajax({\n");
      out.write("							url : \"/fm/weeklyonetag\",\n");
      out.write("							type : \"get\",\n");
      out.write("							dataType : \"json\",\n");
      out.write("							success : function(data) {\n");
      out.write("								console.log(\"인기 태그  게시글 : \" + data);\n");
      out.write("\n");
      out.write("								var str = JSON.stringify(data);\n");
      out.write("								var json = JSON.parse(str);\n");
      out.write("\n");
      out.write("								values = \"<input type='submit' value='더 많은 결과 보기'><br><br>\";\n");
      out.write("								for ( var i in json.olist) {\n");
      out.write("									values +=\n");
      out.write("\n");
      out.write("									\"<div class='card'>\"\n");
      out.write("											+ \"<img class='card-img-top' src='https://dummyimage.com/450x300/dee2e6/6c757d.jpg' alt='...' />\"\n");
      out.write("											+ \"<div class='card-body'>\"\n");
      out.write("											+ \"<h5 class='card-title'>\"\n");
      out.write("											+ json.olist[i].nickName\n");
      out.write("											+ \"님</h5>\"\n");
      out.write("											+ \"<p class='card-text'> 작성 날짜: \"\n");
      out.write("											+ json.olist[i].trailDate\n");
      out.write("											+ \"<br> JSON\"\n");
      out.write("											+ json.olist[i].trailJson\n");
      out.write("											+ \"<br> 좋아요 : \"\n");
      out.write("											+ json.olist[i].trailGood\n");
      out.write("											+ \" <br></p>조회수 : \"\n");
      out.write("											+ json.olist[i].trailCount\n");
      out.write("											+ \"<br>\"\n");
      out.write("											+ \"<a href='/fm/tdetail?trailId=\"\n");
      out.write("											+ json.olist[i].trailId\n");
      out.write("											+ \"' class='btn btn-primary'>상세보기</a>\"\n");
      out.write("											+ \"</div>\" + \"</div>\";\n");
      out.write("								}\n");
      out.write("								$('#onetag').html($('#onetag').html() + values);\n");
      out.write("							},\n");
      out.write("\n");
      out.write("							error : function(xhr, status, error) {\n");
      out.write("								console.error(\"인기 태그 게시글 가져오기 에러 : \", error);\n");
      out.write("							}\n");
      out.write("\n");
      out.write("						});//ajax\n");
      out.write("\n");
      out.write("			});//document ready\n");
      out.write("		</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write(" 	<div class=\"wrapper\" style=\"text-align: center;\">\n");
      out.write("        <form id=\"tagselectform\" class=\"form1\" action=\"/fm/tagnicknamesearch\" method=\"post\">\n");
      out.write("            <input type=\"search\" name=\"keyword\" id=\"searchKeyword\" placeholder=\"검색할 유저or태그를 입력하세요\" style=\"width: 300px;\">\n");
      out.write("            <input type=\"submit\" value=\"검색\">\n");
      out.write("        </form>\n");
      out.write("    \n");
      out.write("    </div>\n");
      out.write("  \n");
      out.write("		<br> <br> <br>\n");
      out.write("\n");
      out.write("		<header>\n");
      out.write("\n");
      out.write("\n");
      out.write("			<div style=\"text-align: center;\">\n");
      out.write("				<form id=\"coming\" action=\"/fm/todayposts\" method=\"post\">\n");
      out.write("					<h2>🎆오늘의 인기 게시글 보기🎆</h2>\n");
      out.write("					<input type=\"submit\" value=\"확인\">\n");
      out.write("				</form>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("			<form id=\"selectWeeklycount\" action=\"/fm/viewsmax\">\n");
      out.write("				<h2>최다 조회수 게시글(주간)</h2>\n");
      out.write("			</form>\n");
      out.write("			<br> <br> <br>\n");
      out.write("\n");
      out.write("			\n");
      out.write("			<form id=\"selectWeeklygood\" action=\"/fm/goodviewmax\">\n");
      out.write("				<br> <br> <br> <br> <br> <br> <br>\n");
      out.write("				<br> <br> <br> <br> <br> <br> <br>\n");
      out.write("				<br> <br> <br>\n");
      out.write("				<h2>최다 좋아요 게시글(주간)</h2>\n");
      out.write("			</form>\n");
      out.write("\n");
      out.write("			<br> <br> <br>\n");
      out.write("			<hr>\n");
      out.write("			<!-- 인기 태그 게시글 보여주기  -->\n");
      out.write("			<form id=\"onetag\" action=\"/fm/weeklyonetagview\">\n");
      out.write("				<br> <br> <br> <br> <br> <br> <br>\n");
      out.write("				<br> <br> <br> <br> <br> <br> <br>\n");
      out.write("				<br> <br> <br>\n");
      out.write("\n");
      out.write("				<h2>최상위 태그 추천 게시글</h2>\n");
      out.write("\n");
      out.write("			</form>\n");
      out.write("\n");
      out.write("			\n");
      out.write("\n");
      out.write("\n");
      out.write("		</header>\n");
      out.write("	</div>\n");
      out.write("	<script\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js\"\n");
      out.write("		integrity=\"sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm\"\n");
      out.write("		crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<br><br>\n");
      out.write("	<br><br>\n");
      out.write("	<br><br>\n");
      out.write("	<br><br>\n");
      out.write("	<br><br>\n");
      out.write("	<br><br>\n");
      out.write("	<br><br>\n");
      out.write("	<br><br>\n");
      out.write("	<br><br>\n");
      out.write("	<br><br>\n");
      out.write("	<br><br>\n");
      out.write("	<br><br>\n");
      out.write("	\n");
      out.write("\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("	  <footer class=\"d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top\">\r\n");
      out.write("		<p class=\"col-md-4 mb-0 text-body-secondary\">&copy; 2023 Team Phoenix</p>\r\n");
      out.write("	\r\n");
      out.write("<!-- 		<a href=\"/fm/menu.jsp\" class=\"col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none\"> -->\r\n");
      out.write("<!-- 		  <svg class=\"bi me-2\" width=\"40\" height=\"32\"><use xlink:href=\"#bootstrap\"/></svg> -->\r\n");
      out.write("<!-- 		</a> -->\r\n");
      out.write("		</footer>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
