/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-06 13:25:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;
import java.util.ArrayList;
import trail.model.vo.Trail;
import follow.model.vo.Follow;
import member.model.vo.Member;
import java.util.ArrayList;
import trail.model.vo.Trail;
import follow.model.vo.Follow;
import javax.servlet.http.HttpSession;

public final class anotherProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/member/../common/navbar.jsp", Long.valueOf(1694005937110L));
    _jspx_dependants.put("/views/member/../common/head.jsp", Long.valueOf(1693643825518L));
    _jspx_dependants.put("/views/member/../common/footer.jsp", Long.valueOf(1693144244000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.servlet.http.HttpSession");
    _jspx_imports_classes.add("follow.model.vo.Follow");
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("trail.model.vo.Trail");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"/fm/views/common/error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	Member member = (Member)request.getAttribute("member");
	ArrayList<Trail> list = (ArrayList<Trail>)request.getAttribute("list");
	ArrayList<Follow> followeelist = (ArrayList<Follow>)request.getAttribute("followeelist");
	ArrayList<Follow> followerlist = (ArrayList<Follow>)request.getAttribute("followerlist");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\" data-bs-theme=\"auto\">\n");
      out.write("<head>\n");
      out.write("	<link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"/fm/apple-touch-icon.png\">\n");
      out.write("<link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"/fm/favicon-32x32.png\">\n");
      out.write("<link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"/fm/favicon-16x16.png\">\n");
      out.write("<link rel=\"manifest\" href=\"/fm/site.webmanifest\">\n");
      out.write("\n");
      out.write("		<meta charset=\"utf-8\">\n");
      out.write("		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("		<meta name=\"description\" content=\"\">\n");
      out.write("		<title>FollowMe! Trail Sharing SNS</title>\n");
      out.write("	\n");
      out.write("<!-- 		<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/@docsearch/css@3\"> -->\n");
      out.write("\n");
      out.write("<!-- 부트스트랩, 부트스트랩 아이콘 css, js,  jquery 로드 -->	\n");
      out.write("	<link href=\"/fm/resources/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css\">\n");
      out.write("\n");
      out.write("	<script src=\"/fm/resources/js/jquery-3.7.0.min.js\"></script>\n");
      out.write("	<script src=\"/fm/resources/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- 수제 css , js 로드 -->\n");
      out.write("	<link href=\"/fm/resources/css/fm.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("	<script src=\"/fm/resources/js/fm.js\"></script>\n");
      out.write("	\n");
      out.write("\r\n");
      out.write("<!-- <head> 윗 부분은 head.jsp에서 일괄 관리합니다.\r\n");
      out.write("개발용 임시 <style> <script> 는 아래 </head> 위에 작성해 주세요 -->\r\n");
      out.write("<link href=\"/fm/resources/css/myprofileStyle.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("<script>\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("    	var followmid = '");
      out.print( member.getmId() );
      out.write("';\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: '/fm/followcheck', \r\n");
      out.write("            type: 'get',\r\n");
      out.write("            dataType: 'json',\r\n");
      out.write("            data: {\r\n");
      out.write("            	followmid: followmid\r\n");
      out.write("            },\r\n");
      out.write("            success: function(data) {\r\n");
      out.write("                if (data.isFollowing === 'N') {\r\n");
      out.write("                    $('#followButtonDiv').show();\r\n");
      out.write("                } else {\r\n");
      out.write("                    $('#followButtonDiv').hide();\r\n");
      out.write("                }\r\n");
      out.write("            },\r\n");
      out.write("            error : function(xhr, status, error) {\r\n");
      out.write("				console.error(\"팔로우 과정중(ajax) : \", error);\r\n");
      out.write("			}\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<!-- 상단 고정 내비게이션 바 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member loginMember = (Member)session.getAttribute("loginMember");


      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("        var navLinks = document.querySelectorAll(\".nav-li a\");\r\n");
      out.write("\r\n");
      out.write("        for (var i = 0; i < navLinks.length; i++) {\r\n");
      out.write("            navLinks[i].addEventListener(\"mouseover\", function (event) {\r\n");
      out.write("                this.classList.add(\"highlighted\");\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            navLinks[i].addEventListener(\"mouseout\", function (event) {\r\n");
      out.write("                this.classList.remove(\"highlighted\");\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"top-bar\"></div>\r\n");
      out.write("<div class=\"head-div2\">\r\n");
      out.write("	<div class=\"nav-div2 container\">\r\n");
      out.write("		<ul class=\"nav-ul2\">\r\n");
      out.write("			<li class=\"nav-li2\"><a href=\"/fm/tlist\">HOME</a></li>\r\n");
      out.write("			<li class=\"nav-li2\"><a href=\"/fm/views/trail/create.jsp\">TRAIL</a></li>\r\n");
      out.write("			<li class=\"nav-li2\"><a href=\"/fm/msgcol\">MESSAGE</a></li>\r\n");
      out.write("			<li class=\"nav-li2\"><a href=\"/fm/flist?mid=");
      out.print( loginMember.getmId() );
      out.write("\">FOLLOW</a></li>\r\n");
      out.write("			<li class=\"nav-li2\" id=\"myProfile\"><a href=\"/fm/myinfo\">MYPROFILE</a></li>\r\n");
      out.write("			<li class=\"nav-li2\"><a href=\"/fm/nlist\">NOTICE</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"nav-search2\">\r\n");
      out.write("	<img class=\"search-icon2\" src=\"/fm/resources/img/search.jpeg\" onclick=\"search();\">\r\n");
      out.write("	<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"25\" height=\"25\" fill=\"currentColor\" class=\"bi bi-box-arrow-right\" viewBox=\"0 0 16 16\" onclick=\"logout();\" style=\"cursor: pointer;\">\r\n");
      out.write("	    <path fill-rule=\"evenodd\" d=\"M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z\"/>\r\n");
      out.write("	    <path fill-rule=\"evenodd\" d=\"M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z\"/>\r\n");
      out.write("	</svg>\r\n");
      out.write("	</svg>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"main-logo-img2\">\r\n");
      out.write("		<a href=\"/fm/pheonix.jsp\"><img class=\"logo-img2\" src=\"/fm/resources/img/Followmelogo.png\"></a>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function logout(){\r\n");
      out.write("	location.href=\"/fm/logout\"\r\n");
      out.write("}\r\n");
      out.write("function search(){\r\n");
      out.write("	location.href=\"/fm/views/trail/search.jsp\"\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Header-->\r\n");
      out.write("	<header class=\"bg-navy py-5\">\r\n");
      out.write("		<div class=\"container px-4 px-lg-5 my-5\">\r\n");
      out.write("			<div class=\"text-center text-white\">\r\n");
      out.write("				<div class=\"myinfo-card\">\r\n");
      out.write("					<div style=\"border: 1px solid #ccc;overflow: hidden;width:50%;margin:auto;width: 150px;height: 150px;border-radius:70%;background-color:white;\">\r\n");
      out.write("					<img src=\"/fm/resources/images/");
      out.print( member.getProfilePic()!=null?member.getProfilePic():"user.png" );
      out.write("\" \r\n");
      out.write("					style=\"width: 150px;height: 150px;object-fit: cover;border-radius:70%;\">\r\n");
      out.write("					</div>\r\n");
      out.write("				<br>\r\n");
      out.write("				<h1 class=\"fw-bolder image-container\">\r\n");
      out.write("				");
 if(member.getNickName() != null) { 
      out.write("\r\n");
      out.write("		            ");
      out.print( member.getNickName() );
      out.write("\r\n");
      out.write("		        ");
 } else { 
      out.write("\r\n");
      out.write("		            user\r\n");
      out.write("		        ");
 } 
      out.write("\r\n");
      out.write("				</h1>\r\n");
      out.write("				<p class=\"lead fw-normal mb-0\" style=\"color:black;\">");
      out.print( member.getEmail() );
      out.write("</p>\r\n");
      out.write("				<p class=\"lead fw-normal text-white-50 mb-0\" style=\"font-size:15px\"><a href=\"/fm/flist?mid=");
      out.print(member.getmId());
      out.write("\" style=\"font-weight: normal;text-decoration: none;color:grey;\">팔로이: ");
      out.print(followeelist.size() );
      out.write("&nbsp; &nbsp; &nbsp; 팔로워: ");
      out.print(followerlist.size() );
      out.write("</a></p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"myinfo-card2\">\r\n");
      out.write("				<table id=\"outer\" align=\"center\" width=\"500\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th colspan=\"2\" style=\"text-align: left\">\"");
      out.print( member.getmName() );
      out.write("\"님의\r\n");
      out.write("							회원정보입니다\r\n");
      out.write("						</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr style=\"text-align: left\">\r\n");
      out.write("						<th>이메일</th>\r\n");
      out.write("						<td>");
      out.print( member.getEmail() );
      out.write("</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr style=\"text-align: left\">\r\n");
      out.write("						<th>이름</th>\r\n");
      out.write("						<td>");
      out.print( member.getmName() );
      out.write("</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr style=\"text-align: left\">\r\n");
      out.write("					    <th>성별</th>\r\n");
      out.write("					    <td>\r\n");
      out.write("					        ");
 if(member.getGender() != null) { 
      out.write("\r\n");
      out.write("					            ");
      out.print( member.getGender() );
      out.write("\r\n");
      out.write("					        ");
 } else { 
      out.write("\r\n");
      out.write("					            (비공개)\r\n");
      out.write("					        ");
 } 
      out.write("\r\n");
      out.write("					    </td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr style=\"text-align: left\">\r\n");
      out.write("					    <th>전화번호</th>\r\n");
      out.write("					    <td>\r\n");
      out.write("					        ");
 if(member.getPhone() != null) { 
      out.write("\r\n");
      out.write("					            ");
      out.print( member.getPhone() );
      out.write("\r\n");
      out.write("					        ");
 } else { 
      out.write("\r\n");
      out.write("					            (비공개)\r\n");
      out.write("					        ");
 } 
      out.write("\r\n");
      out.write("					    </td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					");
 if(member.getLoginLv() == 6){ 
      out.write("\r\n");
      out.write("					<tr style=\"text-align: left\">\r\n");
      out.write("						<th>회원등급</th>\r\n");
      out.write("						<td>프리미엄 회원</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					");
 } 
      out.write("\r\n");
      out.write("					");
 if(member.getLoginLv() == 7){ 
      out.write("\r\n");
      out.write("					<tr style=\"text-align: left\">\r\n");
      out.write("						<th>회원등급</th>\r\n");
      out.write("						<td>신</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					");
 } 
      out.write("\r\n");
      out.write("					<tr style=\"text-align: left\">\r\n");
      out.write("						<th colspan=\"2\">\r\n");
      out.write("						<br>\r\n");
      out.write("						<div class=\"d-flex\">\r\n");
      out.write("						&nbsp;<button type=\"button\" class=\"btn btn-outline-edit\"onclick=\"sendMessage();\">메세지보내기</button>\r\n");
      out.write("						&nbsp;\r\n");
      out.write("						<div id=\"followButtonDiv\">\r\n");
      out.write("						    <button type=\"button\" class=\"btn btn-outline-edit\" onclick=\"follow();\">팔로우하기</button>\r\n");
      out.write("						</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	<!-- Section-->\r\n");
      out.write("<section class=\"py-5\">\r\n");
      out.write("<hr>\r\n");
      out.write("    <div class=\"container px-4 px-lg-5 mt-5\">\r\n");
      out.write("             <span class=\"badge rounded-pill bg-secondary\" style=\"left: 10%;top:110%;\">등록한 게시물 목록</span>\r\n");
      out.write("             <br><br>\r\n");
      out.write("        <div class=\"row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center\">\r\n");
      out.write("	 		");
if (list.isEmpty()) { 
      out.write("\r\n");
      out.write("	 		<br><br><br>\r\n");
      out.write("         	<p>등록된 게시글이 없습니다.</p>\r\n");
      out.write("         	");
 }else{ 
      out.write("\r\n");
      out.write("          ");
 for (Trail t : list) { 
      out.write("\r\n");
      out.write("          <br><br><br>\r\n");
      out.write("            <div class=\"col mb-5\">\r\n");
      out.write("                <div class=\"card h-100\">\r\n");
      out.write("                    <!-- Product image-->\r\n");
      out.write("                    <img class=\"card-img-top\"\r\n");
      out.write("                        src=\"https://dummyimage.com/450x300/dee2e6/6c757d.jpg\" alt=\"...\" />\r\n");
      out.write("                    <!-- Product details-->\r\n");
      out.write("                    <div class=\"card-body p-4\">\r\n");
      out.write("                        <div class=\"text-center\">\r\n");
      out.write("                            <!-- Product name-->\r\n");
      out.write("                            <h5 class=\"fw-bolder\">");
      out.print( t.getTrailDate() );
      out.write(" </h5>\r\n");
      out.write("                            <!-- Product price-->\r\n");
      out.write("                         ");
      out.print( t.getTrailJson() );
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Product actions-->\r\n");
      out.write("                    <div class=\"card-footer p-4 pt-0 border-top-0 bg-transparent\">\r\n");
      out.write("                        <div class=\"text-center\">\r\n");
      out.write("                          <a class=\"btn btn-outline-dark mt-auto\" href=\"/fm/tdetail?trailId=");
      out.print( t.getTrailId() );
      out.write("\">상세정보</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        	");
 } 
      out.write("           \r\n");
      out.write("        	");
 } 
      out.write("\r\n");
      out.write("        	<br><br><br>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"/fm/resources/js/myprofileStyle.js\"></script>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("	  <footer class=\"d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top\">\r\n");
      out.write("		<p class=\"col-md-4 mb-0 text-body-secondary\">&copy; 2023 Team Phoenix</p>\r\n");
      out.write("	\r\n");
      out.write("<!-- 		<a href=\"/fm/menu.jsp\" class=\"col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none\"> -->\r\n");
      out.write("<!-- 		  <svg class=\"bi me-2\" width=\"40\" height=\"32\"><use xlink:href=\"#bootstrap\"/></svg> -->\r\n");
      out.write("<!-- 		</a> -->\r\n");
      out.write("		</footer>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("	function sendMessage(){\r\n");
      out.write("		location.href = \"/fm/rsend?mid=");
      out.print(member.getmId());
      out.write("\";\r\n");
      out.write("	}\r\n");
      out.write("	function follow(){\r\n");
      out.write("		location.href = \"/fm/follow?mid=");
      out.print(member.getmId());
      out.write("\";\r\n");
      out.write("	}\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
