/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-06 14:58:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;
import java.util.ArrayList;
import trail.model.vo.Trail;
import follow.model.vo.Follow;
import member.model.vo.Member;
import java.util.ArrayList;
import trail.model.vo.Trail;
import follow.model.vo.Follow;
import javax.servlet.http.HttpSession;
import common.Paging;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/views/member/../common/navbar.jsp", Long.valueOf(1694005937110L));
    _jspx_dependants.put("/views/member/../common/head.jsp", Long.valueOf(1693643825518L));
    _jspx_dependants.put("/views/member/../common/footer.jsp", Long.valueOf(1693144244000L));
    _jspx_dependants.put("/views/member/../common/pagingView.jsp", Long.valueOf(1693473586345L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.servlet.http.HttpSession");
    _jspx_imports_classes.add("common.Paging");
    _jspx_imports_classes.add("follow.model.vo.Follow");
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("trail.model.vo.Trail");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"/fm/views/common/error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	Member member = (Member)session.getAttribute("loginMember");
	ArrayList<Trail> list = (ArrayList<Trail>)request.getAttribute("list");
	ArrayList<Follow> followeelist = (ArrayList<Follow>)request.getAttribute("followeelist");
	ArrayList<Follow> followerlist = (ArrayList<Follow>)request.getAttribute("followerlist");
	int nowpage = ((Integer)request.getAttribute("currentPage")).intValue();


      out.write("\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\" data-bs-theme=\"auto\">\n");
      out.write("<head>\n");
      out.write("	<link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"/fm/apple-touch-icon.png\">\n");
      out.write("<link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"/fm/favicon-32x32.png\">\n");
      out.write("<link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"/fm/favicon-16x16.png\">\n");
      out.write("<link rel=\"manifest\" href=\"/fm/site.webmanifest\">\n");
      out.write("\n");
      out.write("		<meta charset=\"utf-8\">\n");
      out.write("		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("		<meta name=\"description\" content=\"\">\n");
      out.write("		<title>FollowMe! Trail Sharing SNS</title>\n");
      out.write("	\n");
      out.write("<!-- 		<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/@docsearch/css@3\"> -->\n");
      out.write("\n");
      out.write("<!-- 부트스트랩, 부트스트랩 아이콘 css, js,  jquery 로드 -->	\n");
      out.write("	<link href=\"/fm/resources/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css\">\n");
      out.write("\n");
      out.write("	<script src=\"/fm/resources/js/jquery-3.7.0.min.js\"></script>\n");
      out.write("	<script src=\"/fm/resources/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- 수제 css , js 로드 -->\n");
      out.write("	<link href=\"/fm/resources/css/fm.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("	<script src=\"/fm/resources/js/fm.js\"></script>\n");
      out.write("	\n");
      out.write("\r\n");
      out.write("<!-- <head> 윗 부분은 head.jsp에서 일괄 관리합니다.\r\n");
      out.write("개발용 임시 <style> <script> 는 아래 </head> 위에 작성해 주세요 -->\r\n");
      out.write("<link href=\"/fm/resources/css/myprofileStyle.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<!-- 상단 고정 내비게이션 바 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member loginMember = (Member)session.getAttribute("loginMember");


      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("        var navLinks = document.querySelectorAll(\".nav-li a\");\r\n");
      out.write("\r\n");
      out.write("        for (var i = 0; i < navLinks.length; i++) {\r\n");
      out.write("            navLinks[i].addEventListener(\"mouseover\", function (event) {\r\n");
      out.write("                this.classList.add(\"highlighted\");\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            navLinks[i].addEventListener(\"mouseout\", function (event) {\r\n");
      out.write("                this.classList.remove(\"highlighted\");\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"top-bar\"></div>\r\n");
      out.write("<div class=\"head-div2\">\r\n");
      out.write("	<div class=\"nav-div2 container\">\r\n");
      out.write("		<ul class=\"nav-ul2\">\r\n");
      out.write("			<li class=\"nav-li2\"><a href=\"/fm/tlist\">HOME</a></li>\r\n");
      out.write("			<li class=\"nav-li2\"><a href=\"/fm/views/trail/create.jsp\">TRAIL</a></li>\r\n");
      out.write("			<li class=\"nav-li2\"><a href=\"/fm/msgcol\">MESSAGE</a></li>\r\n");
      out.write("			<li class=\"nav-li2\"><a href=\"/fm/flist?mid=");
      out.print( loginMember.getmId() );
      out.write("\">FOLLOW</a></li>\r\n");
      out.write("			<li class=\"nav-li2\" id=\"myProfile\"><a href=\"/fm/myinfo\">MYPROFILE</a></li>\r\n");
      out.write("			<li class=\"nav-li2\"><a href=\"/fm/nlist\">NOTICE</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"nav-search2\">\r\n");
      out.write("	<img class=\"search-icon2\" src=\"/fm/resources/img/search.jpeg\" onclick=\"search();\">\r\n");
      out.write("	<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"25\" height=\"25\" fill=\"currentColor\" class=\"bi bi-box-arrow-right\" viewBox=\"0 0 16 16\" onclick=\"logout();\" style=\"cursor: pointer;\">\r\n");
      out.write("	    <path fill-rule=\"evenodd\" d=\"M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z\"/>\r\n");
      out.write("	    <path fill-rule=\"evenodd\" d=\"M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z\"/>\r\n");
      out.write("	</svg>\r\n");
      out.write("	</svg>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"main-logo-img2\">\r\n");
      out.write("		<a href=\"/fm/pheonix.jsp\"><img class=\"logo-img2\" src=\"/fm/resources/img/Followmelogo.png\"></a>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function logout(){\r\n");
      out.write("	location.href=\"/fm/logout\"\r\n");
      out.write("}\r\n");
      out.write("function search(){\r\n");
      out.write("	location.href=\"/fm/views/trail/search.jsp\"\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".nav-li2:nth-child(5):hover a {\r\n");
      out.write("    color: #000;\r\n");
      out.write("}\r\n");
      out.write(".nav-li2:nth-child(5):hover a::before {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- Navigation-->\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navbar-light bg-light \">\r\n");
      out.write("		<div class=\"container px-4 px-lg-5\">\r\n");
      out.write("			<a class=\"navbar-brand\" href=\"#!\">내정보</a>\r\n");
      out.write("			<button class=\"navbar-toggler\" type=\"button\"\r\n");
      out.write("				data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\"\r\n");
      out.write("				aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("				aria-label=\"Toggle navigation\">\r\n");
      out.write("				<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("			</button>\r\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("				<ul class=\"navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4\">\r\n");
      out.write("					<li class=\"nav-item dropdown\"><a\r\n");
      out.write("						class=\"nav-link dropdown-toggle\" id=\"navbarDropdown\" href=\"#\"\r\n");
      out.write("						role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">수정하기</a>\r\n");
      out.write("						<ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("							<li><a class=\"dropdown-item\"\r\n");
      out.write("								href=\"javascript:location.href='/fm/moveup?email=");
      out.print( member.getEmail() );
      out.write("';\">내정보 수정</a></li>\r\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"/fm/flist?mid=");
      out.print(member.getmId());
      out.write("\">팔로우 관리</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("           		<a href=\"/fm/tflist\" style=\"color: gray;\">팔로워 게시글</a>\r\n");
      out.write("				&nbsp; | &nbsp;\r\n");
      out.write("				<a href=\"/fm/tbook\" style=\"color: gray;\">북마크 게시글</a>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<!-- Header-->\r\n");
      out.write("	<header class=\"py-5 bg-navy\">\r\n");
      out.write("		<div class=\"container px-4 px-lg-5 my-5\">\r\n");
      out.write("			<div class=\"text-center text-white\">\r\n");
      out.write("				<div class=\"myinfo-card\">\r\n");
      out.write("					<div style=\"border: 1px solid #ccc;overflow: hidden;width:50%;margin:auto;width: 150px;height: 150px;border-radius:70%;background-color:white;\">\r\n");
      out.write("					<img src=\"/fm/resources/images/");
      out.print( member.getProfilePic()!=null?member.getProfilePic():"user.png" );
      out.write("\" \r\n");
      out.write("					style=\"width: 150px;height: 150px;object-fit: cover;border-radius:70%;\">\r\n");
      out.write("					</div>\r\n");
      out.write("				<br>\r\n");
      out.write("				<h1 class=\"fw-bolder image-container\">\r\n");
      out.write("				");
 if(member.getNickName() != null) { 
      out.write("\r\n");
      out.write("		            ");
      out.print( member.getNickName() );
      out.write("\r\n");
      out.write("		        ");
 } else { 
      out.write("\r\n");
      out.write("		            user\r\n");
      out.write("		        ");
 } 
      out.write("\r\n");
      out.write("				</h1>\r\n");
      out.write("				<p class=\"lead fw-normal mb-0\" style=\"color:black;\">");
      out.print( member.getEmail() );
      out.write("</p>\r\n");
      out.write("				<p class=\"lead fw-normal text-white-50 mb-0\" style=\"font-size:15px\"><a href=\"/fm/flist?mid=");
      out.print(member.getmId());
      out.write("\" style=\"font-weight: normal;text-decoration: none;color:grey;\">팔로이: ");
      out.print(followeelist.size() );
      out.write("&nbsp; &nbsp; &nbsp; 팔로워: ");
      out.print(followerlist.size() );
      out.write("</a></p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"myinfo-card2\">\r\n");
      out.write("				<table id=\"outer\" align=\"center\" width=\"500\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th colspan=\"2\" style=\"text-align: left\">\"");
      out.print( member.getmName() );
      out.write("\"님의\r\n");
      out.write("							회원정보입니다\r\n");
      out.write("						</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr style=\"text-align: left\">\r\n");
      out.write("						<th>이메일</th>\r\n");
      out.write("						<td>");
      out.print( member.getEmail() );
      out.write("</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr style=\"text-align: left\">\r\n");
      out.write("						<th>이름</th>\r\n");
      out.write("						<td>");
      out.print( member.getmName() );
      out.write("</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr style=\"text-align: left\">\r\n");
      out.write("					    <th>성별</th>\r\n");
      out.write("					    <td>\r\n");
      out.write("					        ");
 if(member.getGender() != null) { 
      out.write("\r\n");
      out.write("					            ");
      out.print( member.getGender() );
      out.write("\r\n");
      out.write("					        ");
 } else { 
      out.write("\r\n");
      out.write("					            (미지정)\r\n");
      out.write("					        ");
 } 
      out.write("\r\n");
      out.write("					    </td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr style=\"text-align: left\">\r\n");
      out.write("					    <th>전화번호</th>\r\n");
      out.write("					    <td>\r\n");
      out.write("					        ");
 if(member.getPhone() != null) { 
      out.write("\r\n");
      out.write("					            ");
      out.print( member.getPhone() );
      out.write("\r\n");
      out.write("					        ");
 } else { 
      out.write("\r\n");
      out.write("					            (전화번호를 추가해주세요)\r\n");
      out.write("					        ");
 } 
      out.write("\r\n");
      out.write("					    </td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					");
 if(member.getLoginLv() == 6){ 
      out.write("\r\n");
      out.write("					<tr style=\"text-align: left\">\r\n");
      out.write("						<th>회원등급</th>\r\n");
      out.write("						<td>프리미엄 회원</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					");
 } 
      out.write("\r\n");
      out.write("					");
 if(member.getLoginLv() == 7){ 
      out.write("\r\n");
      out.write("					<tr style=\"text-align: left\">\r\n");
      out.write("						<th>회원등급</th>\r\n");
      out.write("						<td>신</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					");
 } 
      out.write("\r\n");
      out.write("					<tr style=\"text-align: left\">\r\n");
      out.write("						<th colspan=\"2\">\r\n");
      out.write("						<br>\r\n");
      out.write("								<button type=\"button\" class=\"btn btn-outline-edit\" onclick=\"javascript:location.href='/fm/moveup?email=");
      out.print( member.getEmail() );
      out.write("';\">내정보 수정</button>\r\n");
      out.write("								&nbsp; <button type=\"button\" class=\"btn btn-outline-edit\"onclick=\"showToast();\">탈퇴하기</button>\r\n");
      out.write("						</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"hidden-toast\"\r\n");
      out.write("				style=\"margin: 0 auto; width: 80%; display: none; position: fixed; top: 30%; left: 40%;z-index:9;\">\r\n");
      out.write("				<div class=\"toast fade show \" role=\"alert\" aria-live=\"assertive\"\r\n");
      out.write("					aria-atomic=\"true\"\r\n");
      out.write("					style=\"width: 500px; height: 300px;\">\r\n");
      out.write("					<div class=\"toast-header\">\r\n");
      out.write("						<svg class=\"bd-placeholder-img rounded me-2\" width=\"20\"\r\n");
      out.write("							height=\"20\" xmlns=\"http://www.w3.org/2000/svg\" aria-hidden=\"true\"\r\n");
      out.write("							preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\r\n");
      out.write("							<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-exclamation-square\" viewBox=\"0 0 16 16\">\r\n");
      out.write("							  <path d=\"M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z\"/>\r\n");
      out.write("							  <path d=\"M7.002 11a1 1 0 1 1 2 0 1 1 0 0 1-2 0zM7.1 4.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 4.995z\"/>\r\n");
      out.write("							</svg></svg>\r\n");
      out.write("\r\n");
      out.write("						<strong class=\"me-auto\">경고</strong> <small\r\n");
      out.write("							class=\"text-muted\">");
      out.print( member.getEmail() );
      out.write("</small>\r\n");
      out.write("						<button type=\"button\" class=\"btn-close\" onclick=\"displayToast()\"></button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"toast-body\" style=\"color: black; text-align: left;\">\r\n");
      out.write("					    회원 <span style=\"font-weight: bold; color: red;\">탈퇴</span>를 하면 <br>\r\n");
      out.write("					    서비스를 더 이상 이용하실 수 없습니다.<br><br>\r\n");
      out.write("					    회원 탈퇴를 진행하시겠습니까?<br><br><br>\r\n");
      out.write("					    <p style=\"font-size: 12px; color: gray;\">\r\n");
      out.write("					        이후 회원 복구를 원하시면 관리자에게 문의하십시오.\r\n");
      out.write("					    </p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<button class=\"btn btn-outline-secondary\"\r\n");
      out.write("						style=\"bottom: 15px; right: 600px;margin-top:24px;margin-left:250px;\"\r\n");
      out.write("						onclick=\"deleteMember();\">탈퇴하기</button>\r\n");
      out.write("					<button class=\"btn btn-outline-secondary\"\r\n");
      out.write("						style=\"bottom: 15px; right: 530px;margin-top:24px;margin-left:10px;\"\r\n");
      out.write("						onclick=\"displayToast()\">최소</button>\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	<!-- Section-->\r\n");
      out.write("<section class=\"py-5\">\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container px-4 px-lg-5 mt-5\">\r\n");
      out.write("             <span class=\"badge rounded-pill bg-secondary\" style=\"left: 10%;top:110%;\">등록한 게시물 목록</span>\r\n");
      out.write("             <br><br>\r\n");
      out.write("        <div class=\"justify-content-center\">\r\n");
      out.write("	 		");
if (list.isEmpty()) { 
      out.write("\r\n");
      out.write("	 		<br><br><br>\r\n");
      out.write("         	<p>등록된 게시글이 없습니다.</p>\r\n");
      out.write("         	");
 }else{ 
      out.write("\r\n");
      out.write("<div class=\"row justify-content-center\"> <!-- 중앙 정렬을 위한 부분 -->\r\n");
      out.write("            <div class=\"col-md-10\"> <!-- 한 줄에 한 개의 게시글을 나열 -->\r\n");
      out.write("                ");
 for (Trail trail : list) { 
      out.write("\r\n");
      out.write("                ");
 ArrayList<Trail> photoList = (ArrayList<Trail>) request.getAttribute("photoList_" + trail.getTrailId()); 
      out.write("\r\n");
      out.write("                <div class=\"card mb-4\"> <!-- 카드 간 간격 조절 -->\r\n");
      out.write("                 <article class=\"my-3\" id=\"carousel\">\r\n");
      out.write("      <div class=\"bd-heading align-self-start mt-5 mb-3 mt-xl-0 mb-xl-2\">\r\n");
      out.write("        <h3>");
      out.print( trail.getNickName() );
      out.write("</h3>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div>\r\n");
      out.write("        <div class=\"bd-example-snippet bd-code-snippet\"><div class=\"bd-example m-0 border-0\">\r\n");
      out.write("        <div id=\"carouselExampleCaptions");
      out.print( trail.getTrailId() );
      out.write("\" class=\"carousel slide\" data-bs-ride=\"carousel\">\r\n");
      out.write("          <div id = \"carouselind");
      out.print( trail.getTrailId() );
      out.write("\" class=\"carousel-indicators\">\r\n");
      out.write("            ");
 for (int i = 0; i < photoList.size(); i++) { 
      out.write("\r\n");
      out.write("  			");

   			 String buttonClass = "";
   				 if (i == 0) {
     			 buttonClass = "active";
  				  }
 			 
      out.write("\r\n");
      out.write("  				<button type=\"button\" data-bs-target=\"#carouselExampleCaptions");
      out.print( trail.getTrailId() );
      out.write("\" data-bs-slide-to=\"");
      out.print( i );
      out.write("\" class=\"");
      out.print( buttonClass );
      out.write("\" aria-label=\"Slide ");
      out.print( (i + 1) );
      out.write("\"></button>\r\n");
      out.write("			");
 } 
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <!-- Carousel 내용 -->\r\n");
      out.write("          <div id = \"carouselimgs");
      out.print( trail.getTrailId() );
      out.write("\" class=\"carousel-inner\">\r\n");
      out.write("            <div class=\"carousel-item active\" onclick=\"openModal");
      out.print( trail.getTrailId() );
      out.write("(0)\">\r\n");
      out.write("     			 <img src=\"/fm/resources/upfiles/");
      out.print( trail.getTrailId() );
      out.write('/');
      out.print( photoList.get(0).getOriginFileName() );
      out.write("\" class=\"d-block w-100\" alt=\"Image 0\">\r\n");
      out.write("              <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                <h5>First slide label</h5>\r\n");
      out.write("                <p>Some representative placeholder content for the first slide.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            ");
 for (int i = 1; i < photoList.size(); i++) { 
      out.write("\r\n");
      out.write("            <div class=\"carousel-item\" onclick=\"openModal");
      out.print( trail.getTrailId() );
      out.write('(');
      out.print( i );
      out.write(")\">\r\n");
      out.write("     			 <img src=\"/fm/resources/upfiles/");
      out.print( trail.getTrailId() );
      out.write('/');
      out.print( photoList.get(i).getOriginFileName() );
      out.write("\" class=\"d-block w-100\" alt=\"Image 1\" >\r\n");
      out.write("              <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                <h5>Second slide label</h5>\r\n");
      out.write("                <p>Some representative placeholder content for the second slide.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselExampleCaptions");
      out.print( trail.getTrailId() );
      out.write("\" data-bs-slide=\"prev\">\r\n");
      out.write("            <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("            <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("          </button>\r\n");
      out.write("          <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselExampleCaptions");
      out.print( trail.getTrailId() );
      out.write("\" data-bs-slide=\"next\">\r\n");
      out.write("            <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("            <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div></div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </article>\r\n");
      out.write("    \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"carouselExampleModal");
      out.print( trail.getTrailId() );
      out.write("\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"carouselModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-lg\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"carouselModalLabel\">Carousel 모달</h5>\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("       \r\n");
      out.write("\r\n");
      out.write("        <!-- 모달폼 내용 -->\r\n");
      out.write("        <div id=\"carouselExampleModal_");
      out.print( trail.getTrailId() );
      out.write("\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("        <div class=\"carousel-inner\">\r\n");
      out.write("              <div id = \"carouselimgs");
      out.print( trail.getTrailId() );
      out.write("\" class=\"carousel-inner\">\r\n");
      out.write("            <div class=\"carousel-item active\">\r\n");
      out.write("     			 <img src=\"/fm/resources/upfiles/");
      out.print( trail.getTrailId() );
      out.write('/');
      out.print( photoList.get(0).getOriginFileName() );
      out.write("\" class=\"d-block w-100\" alt=\"Image 0\">\r\n");
      out.write("              <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                <h5>First slide label</h5>\r\n");
      out.write("                <p>Some representative placeholder content for the first slide.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            ");
 for (int i = 1; i < photoList.size(); i++) { 
      out.write("\r\n");
      out.write("            <div class=\"carousel-item\">\r\n");
      out.write("     			 <img src=\"/fm/resources/upfiles/");
      out.print( trail.getTrailId() );
      out.write('/');
      out.print( photoList.get(i).getOriginFileName() );
      out.write("\" class=\"d-block w-100\" alt=\"Image 1\" >\r\n");
      out.write("              <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                <h5>Second slide label</h5>\r\n");
      out.write("                <p>Some representative placeholder content for the second slide.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <ol class=\"carousel-indicators\">\r\n");
      out.write("   ");
 for (int i = 0; i < photoList.size(); i++) { 
      out.write("\r\n");
      out.write("  			");

   			 String buttonClass = "";
   				 if (i == 0) {
     			 buttonClass = "active";
  				  }
 			 
      out.write("\r\n");
      out.write("  				<button type=\"button\" data-bs-target=\"#carouselExampleModal_");
      out.print( trail.getTrailId() );
      out.write("\" data-bs-slide-to=\"");
      out.print( i );
      out.write("\" class=\"");
      out.print( buttonClass );
      out.write("\" aria-label=\"Slide ");
      out.print( (i + 1) );
      out.write("\"></button>\r\n");
      out.write("			");
 } 
      out.write("\r\n");
      out.write("</ol>\r\n");
      out.write("\r\n");
      out.write("<!-- Carousel 이전/다음 버튼 수정 -->\r\n");
      out.write("<a class=\"carousel-control-prev\" href=\"#carouselExampleModal_");
      out.print( trail.getTrailId() );
      out.write("\" role=\"button\" data-bs-slide=\"prev\">\r\n");
      out.write("    <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("    <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("</a>\r\n");
      out.write("<a class=\"carousel-control-next\" href=\"#carouselExampleModal_");
      out.print( trail.getTrailId() );
      out.write("\" role=\"button\" data-bs-slide=\"next\">\r\n");
      out.write("    <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("    <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">닫기</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("                \r\n");
      out.write("              <!--   <div class=\"card mb-4\"> 카드 간 간격 조절 -->\r\n");
      out.write("               \r\n");
      out.write("                    <div class=\"card-body\" style=\" cursor: pointer;\" onclick=\"location.href='/fm/tdetail?trailId=");
      out.print( trail.getTrailId() );
      out.write("';\">\r\n");
      out.write("                        <p class=\"card-text\">게시물 ID : ");
      out.print( trail.getTrailId() );
      out.write("</p>\r\n");
      out.write("                        <p class=\"card-text\">글쓴이 ID : ");
      out.print( trail.getmId() );
      out.write("</p>\r\n");
      out.write("                        <p class=\"card-text\">조회수 : ");
      out.print( trail.getTrailCount() );
      out.write("</p>\r\n");
      out.write("                        <p class=\"card-text\">좋아요수 : ");
      out.print( request.getAttribute("goodc" + trail.getTrailId()) );
      out.write("</p>\r\n");
      out.write("                        <p class=\"card-text\">신고처리 여부 : ");
      out.print( trail.getTrailReport() );
      out.write("</p>\r\n");
      out.write("                        <p class=\"card-text\">작성 날짜 : ");
      out.print( trail.getTrailDate() );
      out.write("</p>\r\n");
      out.write("                        <p class=\"card-text\">공개 범위 : ");
      out.print( trail.getTrailRange() );
      out.write("</p>\r\n");
      out.write("                        <a id=\"goodButton_");
      out.print( trail.getTrailId() );
      out.write("\" onclick=\"toggleGood");
      out.print( trail.getTrailId() );
      out.write('(');
      out.write('\'');
      out.print( trail.getTrailId() );
      out.write("'); event.stopPropagation(); return false;\" class=\"btn btn-primary\">좋아요</a>\r\n");
      out.write("                        <a id=\"bookmarkButton_");
      out.print( trail.getTrailId() );
      out.write("\" onclick=\"toggleBookmark");
      out.print( trail.getTrailId() );
      out.write('(');
      out.write('\'');
      out.print( trail.getTrailId() );
      out.write("'); event.stopPropagation(); return false;\" class=\"btn btn-primary\">북마크</a>\r\n");
      out.write("                        <a id=\"reportButton");
      out.print( trail.getTrailId() );
      out.write("\" onclick=\"requestReport");
      out.print( trail.getTrailId() );
      out.write("(); event.stopPropagation(); return false;\" class=\"btn btn-primary\">신고하기</a>\r\n");
      out.write("                        <a href=\"/fm/tdetail?trailId=");
      out.print( trail.getTrailId() );
      out.write("\" class=\"btn btn-primary\">상세정보</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <script type=\"text/javascript\">\r\n");
      out.write("                    // 이 부분에서 JavaScript 코드를 사용할 수 있습니다.\r\n");
      out.write("                    var trailJson = ");
      out.print( trail.getTrailJson() );
      out.write(";\r\n");
      out.write("                    var trailId = '");
      out.print( trail.getTrailId() );
      out.write("';\r\n");
      out.write("                    var isBookmarked = ");
      out.print( request.getAttribute("isBookmarked_" + trail.getTrailId()) );
      out.write(";\r\n");
      out.write("                    var isLiked = ");
      out.print( request.getAttribute("isLiked_" + trail.getTrailId()) );
      out.write(";\r\n");
      out.write("\r\n");
      out.write("                    // 북마크 버튼 상태 초기화\r\n");
      out.write("                    var bookmarkButton_");
      out.print( trail.getTrailId() );
      out.write(" = document.getElementById(\"bookmarkButton_");
      out.print( trail.getTrailId() );
      out.write("\");\r\n");
      out.write("                    if (isBookmarked) {\r\n");
      out.write("                        bookmarkButton_");
      out.print( trail.getTrailId() );
      out.write(".textContent = \"북마크 취소\";\r\n");
      out.write("                        bookmarkButton_");
      out.print( trail.getTrailId() );
      out.write(".classList.add(\"btn-danger\");\r\n");
      out.write("                    } else {\r\n");
      out.write("                        bookmarkButton_");
      out.print( trail.getTrailId() );
      out.write(".textContent = \"북마크\";\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    function toggleBookmark");
      out.print( trail.getTrailId() );
      out.write("(trailId) {\r\n");
      out.write("                        var bookmarkButton = document.getElementById(\"bookmarkButton_\" + trailId);\r\n");
      out.write("                        \r\n");
      out.write("                        if (bookmarkButton.textContent === \"북마크 취소\") {\r\n");
      out.write("                            requestBookmarkCancel");
      out.print( trail.getTrailId() );
      out.write("(trailId);\r\n");
      out.write("                            bookmarkButton.textContent = \"북마크\";\r\n");
      out.write("                            bookmarkButton.classList.remove(\"btn-danger\");\r\n");
      out.write("                        } else {\r\n");
      out.write("                            requestBookmark");
      out.print( trail.getTrailId() );
      out.write("(trailId);\r\n");
      out.write("                            bookmarkButton.textContent = \"북마크 취소\";\r\n");
      out.write("                            bookmarkButton.classList.add(\"btn-danger\");\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    function requestBookmark");
      out.print( trail.getTrailId() );
      out.write("(trailId) {\r\n");
      out.write("                        // 북마크 등록 요청 함수\r\n");
      out.write("                        fetch(`/fm/book?trailId=");
      out.print( trail.getTrailId() );
      out.write("`)\r\n");
      out.write("                        .then(response => response.json())\r\n");
      out.write("                        .then(data => {\r\n");
      out.write("                            if (data.success) {\r\n");
      out.write("                                alert(data.message);\r\n");
      out.write("                            } else {\r\n");
      out.write("                                alert('오류 발생: ' + trailId);\r\n");
      out.write("                            }\r\n");
      out.write("                        })\r\n");
      out.write("                        .catch(error => {\r\n");
      out.write("                            console.error('에러 :', trailId);\r\n");
      out.write("                        });\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    function requestBookmarkCancel");
      out.print( trail.getTrailId() );
      out.write("(trailId) {\r\n");
      out.write("                        // 북마크 취소 요청 함수\r\n");
      out.write("                        fetch(`/fm/bcancel?trailId=");
      out.print( trail.getTrailId() );
      out.write("`)\r\n");
      out.write("                        .then(response => response.json())\r\n");
      out.write("                        .then(data => {\r\n");
      out.write("                            if (data.success) {\r\n");
      out.write("                                alert(data.message);\r\n");
      out.write("                            } else {\r\n");
      out.write("                                alert('오류 발생: ' + trailId);\r\n");
      out.write("                            }\r\n");
      out.write("                        })\r\n");
      out.write("                        .catch(error => {\r\n");
      out.write("                            console.error('에러 :', trailId);\r\n");
      out.write("                        });\r\n");
      out.write("                    }\r\n");
      out.write("                    \r\n");
      out.write("                 // 좋아요 버튼 상태 초기화\r\n");
      out.write("                    var goodButton_");
      out.print( trail.getTrailId() );
      out.write(" = document.getElementById(\"goodButton_");
      out.print( trail.getTrailId() );
      out.write("\");\r\n");
      out.write("                    if (isLiked) {\r\n");
      out.write("                    	goodButton_");
      out.print( trail.getTrailId() );
      out.write(".textContent = \"좋아요 취소\";\r\n");
      out.write("                    	goodButton_");
      out.print( trail.getTrailId() );
      out.write(".classList.add(\"btn-danger\");\r\n");
      out.write("                    } else {\r\n");
      out.write("                    	goodButton_");
      out.print( trail.getTrailId() );
      out.write(".textContent = \"좋아요\";\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    function toggleGood");
      out.print( trail.getTrailId() );
      out.write("(trailId) {\r\n");
      out.write("                        var goodButton = document.getElementById(\"goodButton_\" + trailId);\r\n");
      out.write("                        \r\n");
      out.write("                        if (goodButton.textContent === \"좋아요 취소\") {\r\n");
      out.write("                            requestGoodCancel");
      out.print( trail.getTrailId() );
      out.write("(trailId);\r\n");
      out.write("                            goodButton.textContent = \"좋아요\";\r\n");
      out.write("                            goodButton.classList.remove(\"btn-danger\");\r\n");
      out.write("                        } else {\r\n");
      out.write("                            requestGood");
      out.print( trail.getTrailId() );
      out.write("(trailId);\r\n");
      out.write("                            goodButton.textContent = \"좋아요 취소\";\r\n");
      out.write("                            goodButton.classList.add(\"btn-danger\");\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    function requestGood");
      out.print( trail.getTrailId() );
      out.write("(trailId) {\r\n");
      out.write("                        // 좋아요 등록 요청 함수\r\n");
      out.write("                        fetch(`/fm/good?trailId=");
      out.print( trail.getTrailId() );
      out.write("`)\r\n");
      out.write("                        .then(response => response.json())\r\n");
      out.write("                        .then(data => {\r\n");
      out.write("                            if (data.success) {\r\n");
      out.write("                                alert(data.message);\r\n");
      out.write("                            } else {\r\n");
      out.write("                                alert('오류 발생: ' + trailId);\r\n");
      out.write("                            }\r\n");
      out.write("                        })\r\n");
      out.write("                        .catch(error => {\r\n");
      out.write("                            console.error('에러 :', trailId);\r\n");
      out.write("                        });\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    function requestGoodCancel");
      out.print( trail.getTrailId() );
      out.write("(trailId) {\r\n");
      out.write("                        // 북마크 취소 요청 함수\r\n");
      out.write("                        fetch(`/fm/nogood?trailId=");
      out.print( trail.getTrailId() );
      out.write("`)\r\n");
      out.write("                        .then(response => response.json())\r\n");
      out.write("                        .then(data => {\r\n");
      out.write("                            if (data.success) {\r\n");
      out.write("                                alert(data.message);\r\n");
      out.write("                            } else {\r\n");
      out.write("                                alert('오류 발생: ' + trailId);\r\n");
      out.write("                            }\r\n");
      out.write("                        })\r\n");
      out.write("                        .catch(error => {\r\n");
      out.write("                            console.error('에러 :', trailId);\r\n");
      out.write("                        });\r\n");
      out.write("                    }\r\n");
      out.write("                    function requestReport");
      out.print( trail.getTrailId() );
      out.write("() {\r\n");
      out.write("                        // 현재 페이지의 URL을 추출\r\n");
      out.write("                        var currentURL = window.location.href;\r\n");
      out.write("\r\n");
      out.write("                        // 현재 페이지 URL을 기반으로 리디렉션 수행\r\n");
      out.write("                        var xhr = new XMLHttpRequest();\r\n");
      out.write("                        xhr.open('GET', '/fm/treport?trailId=");
      out.print( trail.getTrailId() );
      out.write("', true);\r\n");
      out.write("                        xhr.onreadystatechange = function () {\r\n");
      out.write("                            if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("                                // 서버에서 리디렉션 완료 후 메시지 표시\r\n");
      out.write("                                alert(\"신고가 접수되었습니다.\");\r\n");
      out.write("                                // 페이지 리로드 또는 필요한 동작 수행\r\n");
      out.write("                                location.reload(); // 페이지 리로드 예시\r\n");
      out.write("                            }\r\n");
      out.write("                        };\r\n");
      out.write("                        xhr.send();\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                </script>\r\n");
      out.write("   <script type=\"text/javascript\">\r\n");
      out.write("   function openModal");
      out.print( trail.getTrailId() );
      out.write("(imageIndex) {\r\n");
      out.write("	    var modalId = `carouselExampleModal");
      out.print( trail.getTrailId() );
      out.write("`;\r\n");
      out.write("	    var modal = document.getElementById(modalId);\r\n");
      out.write("	    var bsModal = new bootstrap.Modal(modal);\r\n");
      out.write("\r\n");
      out.write("	    // 모달이 열릴 때 해당 Carousel을 초기화\r\n");
      out.write("	    modal.addEventListener('shown.bs.modal', function () {\r\n");
      out.write("	        var carouselId = `carouselExampleModal");
      out.print( trail.getTrailId() );
      out.write("`;\r\n");
      out.write("	        var carousel = document.getElementById(carouselId);\r\n");
      out.write("	        var bsCarousel = new bootstrap.Carousel(carousel);\r\n");
      out.write("	        \r\n");
      out.write("\r\n");
      out.write("	        // 클릭한 이미지의 순서에 맞게 Carousel을 설정\r\n");
      out.write("	        bsCarousel.to(imageIndex);\r\n");
      out.write("	    });\r\n");
      out.write("\r\n");
      out.write("	    bsModal.show();\r\n");
      out.write("	}\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   </script>             \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                ");
 } //for 
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>		\r\n");
      out.write("        	");
 } // if 
      out.write("\r\n");
      out.write("        	<br><br><br>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("	<!-- Footer-->\r\n");
      out.write("	<!--   <footer class=\"py-5 bg-dark\">\r\n");
      out.write("            <div class=\"container\"><p class=\"m-0 text-center text-white\">Copyright &copy; Your Website 2023</p></div>\r\n");
      out.write("        </footer> -->\r\n");
      out.write("	<!-- Bootstrap core JS-->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<!-- Core theme JS-->\r\n");
      out.write("	<script src=\"/fm/resources/js/myprofileStyle.js\"></script>\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("    \r\n");

	Paging paging = (Paging)request.getAttribute("paging");
	
	int startPage = paging.getStartPage();
	int endPage = paging.getEndPage();
	int maxPage = paging.getMaxPage();
	int currentPage = paging.getCurrentPage();
	int limit = paging.getLimit();
	
	String urlMapping = paging.getUrlMapping();
	
	String action = (String)request.getAttribute("action");
	String keyword = null, begin = null, end = null;

	if(action != null){
		if(action.equals("date")) {
			begin = (String)request.getAttribute("begin");
			end = (String)request.getAttribute("end");
		}else {
			keyword = (String)request.getAttribute("keyword");
		}
	}

      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');
 if(action == null){ 
      out.write("\r\n");
      out.write("<div style=\"text-align:center;\">\r\n");
      out.write("	");
 if(currentPage <= 1){ 
      out.write("\r\n");
      out.write("		[맨처음] &nbsp;\r\n");
      out.write("	");
 }else{ //currentPage > 1 
      out.write("\r\n");
      out.write("		<a href=\"/fm/");
      out.print( urlMapping );
      out.write("?page=1\">[맨처음]</a> &nbsp;\r\n");
      out.write("	");
 } 
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write('	');
 if((currentPage - 10) < startPage && (currentPage - 10) > 1){  //이전그룹이 있다면 
      out.write("\r\n");
      out.write("		<a href=\"/fm/");
      out.print( urlMapping );
      out.write("?page=");
      out.print( startPage - 10 );
      out.write("\">[이전그룹]</a> &nbsp;\r\n");
      out.write("	");
 }else{ //이전그룹이 없다면 
      out.write("\r\n");
      out.write("		[이전그룹] &nbsp;\r\n");
      out.write("	");
 } 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');
 for(int p = startPage; p <= endPage; p++){ 
			if(p == currentPage){
	
      out.write("\r\n");
      out.write("			<font color=\"blue\" size=\"4\"><b>");
      out.print( p );
      out.write("</b></font>\r\n");
      out.write("	");
     }else{ 
      out.write("\r\n");
      out.write("			<a href=\"/fm/");
      out.print( urlMapping );
      out.write("?page=");
      out.print( p );
      out.write('"');
      out.write('>');
      out.print( p );
      out.write("</a>\r\n");
      out.write("	");
 }} 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');
 if((currentPage + 10) > endPage && (currentPage + 10) < maxPage){  //다음그룹이 있다면 
      out.write("\r\n");
      out.write("		<a href=\"/fm/");
      out.print( urlMapping );
      out.write("?page=");
      out.print( startPage + 10 );
      out.write("\">[다음그룹]</a> &nbsp;\r\n");
      out.write("	");
 }else{ //다음그룹이 없다면 
      out.write("\r\n");
      out.write("		[다음그룹] &nbsp;\r\n");
      out.write("	");
 } 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");
 if(currentPage >= maxPage){ 
      out.write("\r\n");
      out.write("		[맨끝] &nbsp;\r\n");
      out.write("	");
 }else{ //currentPage < maxPage  
      out.write("\r\n");
      out.write("		<a href=\"/fm/");
      out.print( urlMapping );
      out.write("?page=");
      out.print( maxPage );
      out.write("\">[맨끝]</a> &nbsp;\r\n");
      out.write("	");
 } 
      out.write("\r\n");
      out.write("</div>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
 if(action != null && keyword != null){ 
      out.write("\r\n");
      out.write("<div style=\"text-align:center;\">\r\n");
      out.write("	");
 if(currentPage <= 1){ 
      out.write("\r\n");
      out.write("		[맨처음] &nbsp;\r\n");
      out.write("	");
 }else{ //currentPage > 1 
      out.write("\r\n");
      out.write("		<a href=\"/fm/");
      out.print( urlMapping );
      out.write("?page=1&action=");
      out.print( action );
      out.write("&keyword=");
      out.print( keyword );
      out.write("\">[맨처음]</a> &nbsp;\r\n");
      out.write("	");
 } 
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write('	');
 if((currentPage - 10) < startPage && (currentPage - 10) > 1){  //이전그룹이 있다면 
      out.write("\r\n");
      out.write("		<a href=\"/fm/");
      out.print( urlMapping );
      out.write("?page=");
      out.print( startPage - 10 );
      out.write("&action=");
      out.print( action );
      out.write("&keyword=");
      out.print( keyword );
      out.write("\">[이전그룹]</a> &nbsp;\r\n");
      out.write("	");
 }else{ //이전그룹이 없다면 
      out.write("\r\n");
      out.write("		[이전그룹] &nbsp;\r\n");
      out.write("	");
 } 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');
 for(int p = startPage; p <= endPage; p++){ 
			if(p == currentPage){
	
      out.write("\r\n");
      out.write("			<font color=\"blue\" size=\"4\"><b>");
      out.print( p );
      out.write("</b></font>\r\n");
      out.write("	");
     }else{ 
      out.write("\r\n");
      out.write("			<a href=\"/fm/");
      out.print( urlMapping );
      out.write("?page=");
      out.print( p );
      out.write("&action=");
      out.print( action );
      out.write("&keyword=");
      out.print( keyword );
      out.write('"');
      out.write('>');
      out.print( p );
      out.write("</a>\r\n");
      out.write("	");
 }} 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');
 if((currentPage + 10) > endPage && (currentPage + 10) < maxPage){  //다음그룹이 있다면 
      out.write("\r\n");
      out.write("		<a href=\"/fm/");
      out.print( urlMapping );
      out.write("?page=");
      out.print( startPage + 10 );
      out.write("&action=");
      out.print( action );
      out.write("&keyword=");
      out.print( keyword );
      out.write("\">[다음그룹]</a> &nbsp;\r\n");
      out.write("	");
 }else{ //다음그룹이 없다면 
      out.write("\r\n");
      out.write("		[다음그룹] &nbsp;\r\n");
      out.write("	");
 } 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");
 if(currentPage >= maxPage){ 
      out.write("\r\n");
      out.write("		[맨끝] &nbsp;\r\n");
      out.write("	");
 }else{ //currentPage < maxPage  
      out.write("\r\n");
      out.write("		<a href=\"/fm/");
      out.print( urlMapping );
      out.write("?page=");
      out.print( maxPage );
      out.write("&action=");
      out.print( action );
      out.write("&keyword=");
      out.print( keyword );
      out.write("\">[맨끝]</a> &nbsp;\r\n");
      out.write("	");
 } 
      out.write("\r\n");
      out.write("</div>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
 if(action != null && action.equals("date")){ 
      out.write("\r\n");
      out.write("<div style=\"text-align:center;\">\r\n");
      out.write("	");
 if(currentPage <= 1){ 
      out.write("\r\n");
      out.write("		[맨처음] &nbsp;\r\n");
      out.write("	");
 }else{ //currentPage > 1 
      out.write("\r\n");
      out.write("		<a href=\"/fm/");
      out.print( urlMapping );
      out.write("?page=1&action=");
      out.print( action );
      out.write("&begin=");
      out.print( begin );
      out.write("&end=");
      out.print( end );
      out.write("\">[맨처음]</a> &nbsp;\r\n");
      out.write("	");
 } 
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write('	');
 if((currentPage - 10) < startPage && (currentPage - 10) > 1){  //이전그룹이 있다면 
      out.write("\r\n");
      out.write("		<a href=\"/fm/");
      out.print( urlMapping );
      out.write("?page=");
      out.print( startPage - 10 );
      out.write("&action=");
      out.print( action );
      out.write("&begin=");
      out.print( begin );
      out.write("&end=");
      out.print( end );
      out.write("\">[이전그룹]</a> &nbsp;\r\n");
      out.write("	");
 }else{ //이전그룹이 없다면 
      out.write("\r\n");
      out.write("		[이전그룹] &nbsp;\r\n");
      out.write("	");
 } 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');
 for(int p = startPage; p <= endPage; p++){ 
			if(p == currentPage){
	
      out.write("\r\n");
      out.write("			<font color=\"blue\" size=\"4\"><b>");
      out.print( p );
      out.write("</b></font>\r\n");
      out.write("	");
     }else{ 
      out.write("\r\n");
      out.write("			<a href=\"/fm/");
      out.print( urlMapping );
      out.write("?page=");
      out.print( p );
      out.write("&action=");
      out.print( action );
      out.write("&begin=");
      out.print( begin );
      out.write("&end=");
      out.print( end );
      out.write('"');
      out.write('>');
      out.print( p );
      out.write("</a>\r\n");
      out.write("	");
 }} 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');
 if((currentPage + 10) > endPage && (currentPage + 10) < maxPage){  //다음그룹이 있다면 
      out.write("\r\n");
      out.write("		<a href=\"/fm/");
      out.print( urlMapping );
      out.write("?page=");
      out.print( startPage + 10 );
      out.write("\">[다음그룹]</a> &nbsp;\r\n");
      out.write("	");
 }else{ //다음그룹이 없다면 
      out.write("\r\n");
      out.write("		[다음그룹] &nbsp;\r\n");
      out.write("	");
 } 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");
 if(currentPage >= maxPage){ 
      out.write("\r\n");
      out.write("		[맨끝] &nbsp;\r\n");
      out.write("	");
 }else{ //currentPage < maxPage  
      out.write("\r\n");
      out.write("		<a href=\"/fm/");
      out.print( urlMapping );
      out.write("?page=");
      out.print( maxPage );
      out.write("&action=");
      out.print( action );
      out.write("&begin=");
      out.print( begin );
      out.write("&end=");
      out.print( end );
      out.write("\">[맨끝]</a> &nbsp;\r\n");
      out.write("	");
 } 
      out.write("\r\n");
      out.write("</div>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("	  <footer class=\"d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top\">\r\n");
      out.write("		<p class=\"col-md-4 mb-0 text-body-secondary\">&copy; 2023 Team Phoenix</p>\r\n");
      out.write("	\r\n");
      out.write("<!-- 		<a href=\"/fm/menu.jsp\" class=\"col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none\"> -->\r\n");
      out.write("<!-- 		  <svg class=\"bi me-2\" width=\"40\" height=\"32\"><use xlink:href=\"#bootstrap\"/></svg> -->\r\n");
      out.write("<!-- 		</a> -->\r\n");
      out.write("		</footer>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("		function showToast() {\r\n");
      out.write("			var hiddenDiv = document.querySelector('.hidden-toast');\r\n");
      out.write("			if (hiddenDiv !== null) {\r\n");
      out.write("				hiddenDiv.style.display = 'block';\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		function displayToast() {\r\n");
      out.write("			var exitDiv = document.querySelector('.hidden-toast');\r\n");
      out.write("			if (exitDiv !== null) {\r\n");
      out.write("				exitDiv.style.display = 'none';\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		function deleteMember(){\r\n");
      out.write("			location.href = \"/fm/mdel?email=");
      out.print(member.getEmail());
      out.write("&pwd=");
      out.print(member.getPwd());
      out.write("\";\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
